version: "3.7"

services:
  {{ cookiecutter.project_slug }}:
    build:
      context: .
      dockerfile: Containerfile
      args:
        - USER_UID
        - USER_GID

    # Name / Tag created image
    image: {{ cookiecutter.project_slug }}
    # Run interactive with pseudo tty
    stdin_open: true
    tty: true
    # Set up environment
    working_dir: /{{ cookiecutter.project_slug }}

    volumes:
      # Mount current users home in container for access to files
      - type: bind
        source: "."
        target: /{{ cookiecutter.project_slug }}
