version: "3.7"

services:
  {{ cookiecutter.project_slug }}:
    build:
      context: .
      dockerfile: Containerfile

    # Name / Tag created image
    image: {{ cookiecutter.project_slug }}
    # Run interactive with pseudo tty
    stdin_open: true
    tty: true
    # Set up environment
    working_dir: /tmp/{{ cookiecutter.project_slug }}
    # Set user UID:GID
    user: "$CONTAINER_USER"

    volumes:
      # Mount current users home in container for access to files
      - type: bind
        source: "."
        target: /tmp/{{ cookiecutter.project_slug }}
